---

- name: delete deployment config
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: delete service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete imagestream
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ imagestream_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream

- name: delete configmap
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: delete service account
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"
    kind: serviceaccount

- name: delete rolebinding
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ service_account }}-view"
    namespace: "{{ namespace }}"
    kind: rolebinding
