---

# deploy postgresql
- name: check if postgresql is deployed
  oc_obj:
    state: list
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: dc
  register: result

- import_tasks: deploy_postgresql.yml
  when: result.ansible_module_results.stderr is defined and result.ansible_module_results.stderr != ""

- import_tasks: deploy_kafka_connector.yml

# application configmap
- name: copy configmap files from template
  template: src={{ item }} dest={{ work_dir }}/{{ item | basename }}
  with_items:
    - "{{ resources_dir }}/application.properties"
    - "{{ resources_dir }}/jbpm-quartz.properties"

- name: create {{ application_configmap }} configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    name: "{{ application_configmap }}"
    from_file:
      application.properties: "{{ work_dir }}/application.properties"
      jbpm-quartz.properties: "{{ work_dir }}/jbpm-quartz.properties"

# logging configmap
- name: set logging template fact
  set_fact:
    logging_configmap_template: logback.xml

- name: set logging template fact
  set_fact:
    logging_configmap_template: logback-dev.xml
  when: >
    logging_style is defined and logging_style == "dev"

- name: copy {{ logging_configmap }} configmap template
  template:
    src: "{{ resources_dir }}/{{ logging_configmap_template }}"
    dest: "{{ work_dir }}/logback.xml"

- name: create {{ logging_configmap }} configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    name: "{{ logging_configmap }}"
    from_file:
      logback.xml: "{{ work_dir }}/logback.xml"

- name: create {{ service_account }} service account for {{ application_name }} application
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"

- name: give cluster view privileges to {{ service_account }} service account
  oc_adm_policy_user:
    state: present
    oc_binary: "{{ openshift_cli }}"
    resource_kind: role
    resource_name: view
    user: "system:serviceaccount:{{ namespace }}:{{ service_account }}"
    namespace: "{{ namespace }}"
    rolebinding_name: "{{ service_account }}-view"

- import_tasks: deploy_from_source.yml
  when: deploy_from is defined and deploy_from == "source"

- import_tasks: deploy_from_image.yml
  when: deploy_from is defined and deploy_from == "image"