---

- name: remove {{ process_service_postgresql_init_configmap }} configmap
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_init_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: remove {{ process_service_postgresql_configmap }} configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    namespace: "{{ namespace }}"
    name: "{{ process_service_postgresql_configmap }}"

- name: remove {{ process_service_postgresql_credentials_secret }} secret
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_credentials_secret }}"
    namespace: "{{ namespace }}"
    kind: secret

- name: remove {{ process_service_postgresql_service_name }} service
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: remove {{ process_service_postgresql_service_name }} dc
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: remove {{ process_service_postgresql_service_name }} pvc
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: pvc

- name: remove postgresql imagestream
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_image_stream }}"
    namespace: "{{ process_service_postgresql_image_stream_namespace }}"
    kind: is