---

application_name: "{{ responder_simulator_service_application_name }}"

service_account: responder-simulator-service

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 200m
resources_requests_memory: 250Mi

application_configmap: "{{ responder_simulator_service_application_configmap }}"

application_properties: application.properties

imagestream_name: "{{ application_name }}"
image_imagestream_template: responder-simulator-image-is.yml

application_template: responder-simulator.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"

kafka_mission_event_topic: topic-mission-event
kafka_mission_event_groupid: responder-simulator

kafka_responder_update_topic: topic-responder-location-update
kafka_responder_event_topic: topic-responder-event

responder_service_url: "{{ responder_service_application_name }}.{{ namespace_services }}.svc:8080"
responder_service_request_uri: '/responder/'

datagrid_server_list: "{{ datagrid_application_name }}.{{ namespace_datagrid }}.svc:11222"

infinispan_cache_responder_simulator: responder-simulator
