apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: {{ dw_incident_mapping_cache_name }}
spec:
  adminAuth: 
    secretName: basic-auth
  clusterName: {{ datagrid_application_name }}
  name: {{ dw_incident_mapping_cache_name }}
  templateName: org.infinispan.DIST_SYNC
