---

apicurio_registry_operator_packagemanifest: apicurio-registry

apicurio_registry_operator_subscription_starting_csv: ""
apicurio_registry_operator_subscription_automatic_installplan_approval: false
apicurio_registry_operator_subscription_name: apicurio-registry
apicurio_registry_operator_csv_prefix: apicurio-registry
apicurio_registry_operator_deployment_name: apicurio-registry-operator

apicurio_registry_kafka_topic_template: kafka-topic.yml
apicurio_registry_kafka_topic_name_globalid: global-id-topic
apicurio_registry_kafka_topic_name_storage: storage-topic
apicurio_registry_kafka_cluster: "{{ kafka_cluster }}"
apicurio_registry_kafka_topic_partitions: 50
apicurio_registry_kafka_topic_replicas: 3
apicurio_registry_kafka_topic_config: "{}"

apicurio_registry_cr: apicurio-registry
apicurio_registry_cr_template: apicurio-registry-cr.yml
apicurio_registry_replicas: 1
apicurio_registry_persistence: streams
apicurio_registry_application_id: apicurio-registry
apicurio_registry_kafka_bootstrap_servers: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc:9092"