---

- name: delete pgadmin4 route
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ pgadmin4_route_name }}"
    namespace: "{{ namespace }}"
    kind: route

- name: delete pgadmin4 service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ pgadmin4_service_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete pgadmin4 deployment
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ pgadmin4_deployment_name }}"
    namespace: "{{ namespace }}"
    kind: deployment

- name: delete pgadmin4 pvc
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ pgadmin4_pvc_name }}"
    namespace: "{{ namespace }}"
    kind: pvc

- name: delete pgadmin4 secret
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ pgadmin4_secret }}"
    namespace: "{{ namespace }}"
    kind: secret