---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tekton_workspace_pvc_name }}
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce