---

- name: create {{ service_account }} service account for {{ application_name }} application
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"

- name: give cluster view privileges to {{ service_account }} service account
  oc_adm_policy_user:
    state: present
    oc_binary: "{{ openshift_cli }}"
    resource_kind: role
    resource_name: view
    user: "system:serviceaccount:{{ namespace }}:{{ service_account }}"
    namespace: "{{ namespace }}"
    rolebinding_name: "{{ service_account }}-view"

- name: copy {{ application_configmap }} application properties
  template:
    src: "{{ resources_dir }}/app-config.properties"
    dest: "{{ work_dir }}/app-config.properties"

- name: copy {{ application_configmap }} last names
  template:
    src: "{{ resources_dir }}/LNames.txt"
    dest: "{{ work_dir }}/LNames.txt"

- name: copy {{ application_configmap }} first names
  template:
    src: "{{ resources_dir }}/FNames.txt"
    dest: "{{ work_dir }}/FNames.txt"

- name: create {{ application_configmap }} application configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    from_file:
      app-config.properties: "{{ work_dir }}/app-config.properties"
      LNames.txt: "{{ work_dir }}/LNames.txt"
      FNames.txt: "{{ work_dir }}/FNames.txt"

- import_tasks: deploy_from_source.yml
  when: deploy_from is defined and deploy_from == "source"

- import_tasks: deploy_from_image.yml
  when: deploy_from is defined and deploy_from == "image"