apiVersion: applicationmonitoring.integreatly.org/v1alpha1
kind: ApplicationMonitoring
metadata:
  name: middleware-monitoring{{ namespace_postfix }}
spec:
  labelSelector: {{ monitoring_label_value }}
  additionalScrapeConfigSecretName: "integreatly-additional-scrape-configs"
  additionalScrapeConfigSecretKey: "integreatly-additional.yaml"
  prometheusRetention: {{ monitoring_prometheus_retention }}
  prometheusStorageRequest: {{ monitoring_prometheus_storage_request }}
  prometheusInstanceNamespaces: {{ monitoring_namespace }}
  alertmanagerInstanceNamespaces: {{ monitoring_namespace }}
  selfSignedCerts: true
