---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-cluster-monitoring-view-{{ project_admin }}
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: {{ namespace_monitoring }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
