apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator{{ namespace_postfix }}
roleRef:
  name: grafana-operator
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: "{{ monitoring_namespace }}"
userNames:
  - system:serviceaccount:{{ monitoring_namespace }}:grafana-operator
