---

application_name: kafka-consumer-app

service_account: kafka-consumer-app

resources_limits_cpu: 200m
resources_limits_memory: 200Mi
resources_requests_cpu: 100m
resources_requests_memory: 100Mi

application_configmap: "{{ application_name }}"

application_properties: application.properties

imagestream_name: kafka-consumer-app
image_imagestream_template: kafka-consumer-app-is.yml

application_template: kafka-consumer-app.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
kafka_groupid: "{{ application_name }}"
kafka_topic: 