apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
      - name: strimzi-cluster-operator
        image: registry.redhat.io/amq7/amq-streams-operator:1.2.0
        imagePullPolicy: IfNotPresent
        args:
        - /opt/strimzi/bin/cluster_operator_run.sh
        env:
        - name: STRIMZI_NAMESPACE
          value: "*"
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
          value: registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          value: registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE
          value: registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.1.1=registry.redhat.io/amq7/amq-streams-kafka-21:1.2.0
            2.2.1=registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_KAFKA_CONNECT_IMAGES
          value: |
            2.1.1=registry.redhat.io/amq7/amq-streams-kafka-21:1.2.0
            2.2.1=registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.1.1=registry.redhat.io/amq7/amq-streams-kafka-21:1.2.0
            2.2.1=registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.1.0=registry.redhat.io/amq7/amq-streams-kafka-21:1.2.0
            2.2.1=registry.redhat.io/amq7/amq-streams-kafka-22:1.2.0
        - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: registry.redhat.io/amq7/amq-streams-operator:1.2.0
        - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
          value: registry.redhat.io/amq7/amq-streams-operator:1.2.0
        - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
          value: registry.redhat.io/amq7/amq-streams-operator:1.2.0
        - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
          value: registry.redhat.io/amq7/amq-streams-bridge:1.2.0
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: '{{ cluster_operator_resources_cpu_limit }}'
            memory: '{{ cluster_operator_resources_memory_limit }}'
          requests:
            cpu: '{{ cluster_operator_resources_cpu_request }}'
            memory: '{{ cluster_operator_resources_memory_request }}'
  strategy:
    type: Recreate
