---

- name: remove {{ process_service_postgresql_init_configmap }} configmap
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_init_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: remove {{ process_service_postgresql_service_name }} secret
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: secret

- name: remove {{ process_service_postgresql_service_name }} service
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: remove {{ process_service_postgresql_service_name }} dc
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: remove {{ process_service_postgresql_service_name }} pvc
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ process_service_postgresql_service_name }}"
    namespace: "{{ namespace }}"
    kind: pvc