---

jaeger_crd_template: jaeger-crd.yml
jaeger_operator_role_template: jaeger-operator-role.yml
jaeger_operator_rolebinding_template: jaeger-operator-rolebinding.yml
jaeger_operator_template: jaeger-operator.yml
jaeger_cr_template: jaeger-cr.yml
