---

kafka_connect_version: "2.7.0"
kafka_connect_replicas: 1

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"

kafka_connect_template: kafka-connect.yml

kafka_connect_requests_cpu: 100m
kafka_connect_requests_memory: 250M
kafka_connect_limits_cpu: 500m
kafka_connect_limits_memory: 1G

kafka_connect_configmap_metrics_template: kafka-connect-metrics-configmap.yml
kafka_connect_configmap_metrics: kafka-connect-metrics
kafka_connect_configmap_metrics_key: metrics-config.yml

kafka_connect_liveness_probe_initial_delay_seconds: 45
kafka_connect_liveness_probe_timeout_seconds: 5
kafka_connect_readiness_probe_initial_delay_seconds: 15
kafka_connect_readiness_probe_timeout_seconds: 5
