---

- name: create {{ find_application_name }} service account
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ find_application_name }}"
    namespace: "{{ namespace }}"

- name: give cluster view privileges to {{ find_application_name }} service account
  oc_adm_policy_user:
    state: present
    oc_binary: "{{ openshift_cli }}"
    resource_kind: role
    resource_name: view
    user: "system:serviceaccount:{{ namespace }}:{{ find_application_name }}"
    namespace: "{{ namespace }}"
    rolebinding_name: "{{ find_application_name }}-view"

- name: "copy {{ application_properties }} template"
  template:
    src: "{{ application_properties_resource }}"
    dest: "{{ work_dir }}/{{ application_properties }}"

- name: "create {{ cm_name }} configmap"
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ cm_name }}"
    namespace: "{{ namespace }}"
    from_file:
      dir: "{{ work_dir }}/{{ application_properties }}"

- import_tasks: deploy_from_source.yml
  when: deploy_from is defined and deploy_from == "source"

- import_tasks: deploy_from_image.yml
  when: deploy_from is defined and deploy_from == "image"

