---

application_name: "{{ disaster_simulator_service_application_name }}"

service_account: disaster-simulator-service

resources_limits_cpu: 500m
resources_limits_memory: 1536Mi
resources_requests_cpu: 100m
resources_requests_memory: 256Mi

application_configmap: disaster-simulator
application_configmap_key: app-config.properties
lnames_configmap_key: LNames.txt
fnames_configmap_key: FNames.txt

logging_configmap: disaster-simulator-service-logging

application_image: ubi8-openjdk-11:1.3
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: disaster-simulator-service-binary-buildconfig.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: disaster-simulator-service-pipeline.yml

imagestream_name: "{{ application_name }}"
imagestream_template: disaster-simulator-service-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: disaster-simulator-service-image-is.yml

application_template: disaster-simulator-service.yml

kafka_bootstrap_service: "{{ kafka_cluster }}-kafka-bootstrap.{{ namespace_kafka_cluster }}.svc"
kafka_bootstrap_port: 9092
kafka_bootstrap_address: "{{ kafka_bootstrap_service }}:{{ kafka_bootstrap_port }}"
kafka_groupid: responder-sim

kafka_mission_event_topic: topic-mission-event
kafka_responder_update_topic: topic-responder-location-update

logging_style: dev
