---

application_name: "{{ process_viewer_application_name }}"

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 100m
resources_requests_memory: 200Mi

application_configmap: process-viewer
logging_configmap: process-viewer-logging

service_account: process-viewer

application_properties: application-config.yaml

application_image: openjdk-11-rhel8:1.0
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: process-viewer-binary-buildconfig.yml

imagestream_name: "{{ application_name }}"
imagestream_template: process-viewer-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: process-viewer-image-is.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: process-viewer-pipeline.yml

application_template: process-viewer.yml

logging_style: dev

process_viewer_postgresql_host: "{{ process_service_postgresql_service_name}}.{{ namespace_services }}.svc"
process_viewer_postgresql_port: 5432
process_viewer_postgresql_database: "{{ process_service_postgresql_database }}"
process_viewer_postgresql_username: "{{ process_service_postgresql_username }}"
process_viewer_postgresql_password: "{{ process_service_postgresql_password }}"
