---

- name: "create keycloak crd"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: crd
    name: keycloaks.keycloak.org
    files:
      - "{{ resources_dir }}/{{ keycloak_crd_template }}"

- name: "create keycloak realm crd"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: crd
    name: keycloakrealms.keycloak.org
    files:
      - "{{ resources_dir }}/{{ keycloak_realm_crd_template }}"

- name: "create keycloak user crd"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: crd
    name: keycloakusers.keycloak.org
    files:
      - "{{ resources_dir }}/{{ keycloak_user_crd_template }}"

- name: "create keycloak client crd"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: crd
    name: keycloakclients.keycloak.org
    files:
      - "{{ resources_dir }}/{{ keycloak_client_crd_template }}"

- name: "create keycloak backup crd"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: crd
    name: keycloakbackups.keycloak.org
    files:
      - "{{ resources_dir }}/{{ keycloak_backup_crd_template }}"

- name: "create keycloak-operator service account"
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: keycloak-operator
    namespace: "{{ namespace }}"

- name: "create keycloak operator role"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    kind: role
    name: keycloak-operator
    files:
      - "{{ resources_dir }}/{{ keycloak_operator_role_template }}"

- name: "create keycloak operator role binding"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    kind: rolebinding
    name: keycloak-operator
    files:
      - "{{ resources_dir }}/{{ keycloak_operator_rolebinding_template }}"

- name: "deploy keycloak operator"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: deployment
    name: keycloak-operator
    namespace: "{{ namespace }}"
    files:
      - "{{ resources_dir }}/{{ keycloak_operator_template }}"

- name: "wait until operator is deployed"
  shell: "{{ openshift_cli }} get deployment keycloak-operator -o template --template={{ json_template }} -n {{ namespace }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 30
  delay: 10
  changed_when: false

- name: "copy keycloak custom resource template"
  template:
    src: "{{ resources_dir }}/{{ keycloak_cr_template }}"
    dest: "{{ work_dir }}/{{ keycloak_cr_template }}"

- name: "create keycloak custom resource"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: keycloaks.keycloak.org
    name: rhsso
    namespace: "{{ namespace }}"
    files:
      - "{{ work_dir }}/{{ keycloak_cr_template }}"

- name: "create keycloak route"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: route
    name: sso
    namespace: "{{ namespace }}"
    files:
      - "{{ resources_dir }}/{{ keycloak_route_template }}"
