---

- name: "delete keycloak custom resource"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: Keycloak
    name: rhsso
    namespace: "{{ namespace }}"
  when: uninstall_cluster_resources|bool == true

- name: "delete keycloak route"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: route
    name: sso
    namespace: "{{ namespace }}"
  when: uninstall_cluster_resources|bool == true

- name: "delete keycloak operator"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: deployment
    name: keycloak-operator
    namespace: "{{ namespace }}"
  when: uninstall_cluster_resources|bool == true

- name: "delete keycloak operator role binding"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    namespace: "{{ namespace }}"
    kind: rolebinding
    name: keycloak-operator
  when: uninstall_cluster_resources|bool == true

- name: "delete keycloak operator role"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    namespace: "{{ namespace }}"
    kind: role
    name: keycloak-operator
  when: uninstall_cluster_resources|bool == true

- name: "delete keycloak-operator service account"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: serviceaccount
    name: keycloak-operator
    namespace: "{{ namespace }}"
  when: uninstall_cluster_resources|bool == true

- name: "delete {{ namespace }} namespace"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: project
    name: "{{ namespace }}"
  when: uninstall_cluster_resources|bool == true

- name: "delete keycloak crds"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: crd
    name: "{{ item }}"
  loop:
    - keycloaks.keycloak.org
    - keycloakrealms.keycloak.org
    - keycloakusers.keycloak.org
    - keycloakclients.keycloak.org
    - keycloakbackups.keycloak.org
  when: uninstall_cluster_resources|bool == true
