---

application_name: "{{ disaster_service_application_name }}"

service_account: disaster-service

resources_limits_cpu: 500m
resources_limits_memory: 500Mi
resources_requests_cpu: 200m
resources_requests_memory: 200Mi

application_configmap: disaster-service
logging_configmap: disaster-service-logging
sso_configmap: sso-config

application_properties: application-config.yaml

application_image: ubi8-openjdk-11:1.3
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: disaster-service-binary-buildconfig.yml

imagestream_name: "{{ application_name }}"
imagestream_template: disaster-service-imagestream.yml

image_imagestream_name: "{{ application_name }}"
image_imagestream_template: disaster-service-image-is.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: disaster-service-pipeline.yml

application_template: disaster-service.yml

datagrid_service: "{{ datagrid_application_name }}.{{ namespace_datagrid }}.svc"
datagrid_port: 11222

logging_style: dev

prometheus_endpoint_path: "/metrics"
prometheus_endpoint_port: 8080
