{
 "title": "Vertx Service Monitoring",
 "panels": [
  {
   "title": "Total processes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(process_instances)" }
   ]
  },
  {
   "title": "Active processes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(process_instances_active)" }
   ]
  },
  {
   "title": "Completed processes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_instances_completed)"
    }
   ]
  }
 ]
}
{
 "title": "Vertx Service Monitoring",
 "panels": [
  {
   "title": "Active connections",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vertx_http_server_connections) by (service)"
    }
   ]
  },
  {
   "title": "Request count rate by response code",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total[1m])) by (code,service), 0.001)"
    }
   ]
  },
  {
   "title": "Request count rate by code and path",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total[1m])) by (local,code,path,service), 0.001)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Global response time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum[1m])) by (service) / sum(irate(vertx_http_server_responseTime_seconds_count[1m])) by (service)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,service))"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum[1m])) by (path,service) / sum(irate(vertx_http_server_responseTime_seconds_count[1m])) by (path,service)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path,service))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path,service))"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "HTTP Server bytes sent",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesSent_sum[1m])) by (service) / sum(rate(vertx_http_server_bytesSent_count[1m])) by (service)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le,service))"
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesReceived_sum[1m])) by (service) / sum(rate(vertx_http_server_bytesReceived_count[1m])) by (service)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le,service))"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertx_eventbus_handlers" }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertx_eventbus_pending" }
   ]
  },
  {
   "title": "Eventbus: sent rate",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_sent_total[1m])) by (service)"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[1m])) by (service)"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[5m])) by (service)"
    }
   ]
  },
  {
   "title": "Eventbus: received rate",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_received_total[1m])) by (service)"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[1m])) by (service)"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[5m])) by (service)"
    }
   ]
  }
 ]
}
{
 "title": "Vertx Monitoring",
 "panels": [
  {
   "title": "Eventbus processing time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) by (service) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m])) by (service)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,service))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,service))"
    }
   ]
  },
  {
   "title": "Eventbus processing time by address",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_processingTime_seconds_sum[1m])) by (address,service) / sum(irate(vertx_eventbus_processingTime_seconds_count[1m])) by (address,service)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address,service))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address,service))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket[1m])) by (le,address,service))"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Monitoring",
 "panels": [
  {
   "title": "Kafka log size by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_log_size)"
    }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (kafka_log_log_size)"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Monitoring",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"kafka-cluster-kafka-bootstrap\"}[1m])"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ]
  }
 ]
}
{
 "title": "Kafka Monitoring",
 "panels": [
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{service=\"kafka-cluster-kafka-bootstrap\"}[5m]))"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_messagesin_total{service=\"kafka-cluster-kafka-bootstrap\",topic!=\"\"}[5m]))"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Monitoring",
 "panels": [
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesin_total{service=\"kafka-cluster-kafka-bootstrap\",topic!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesout_total{service=\"kafka-cluster-kafka-bootstrap\",topic!=\"\"}[5m]))"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Monitoring",
 "panels": [
  {
   "title": "Offline partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_cluster_partition_underreplicated)"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Monitoring",
 "panels": [
  {
   "title": "ISR expands by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(kafka_server_replicamanager_isrexpands_total[1m]))"
    }
   ]
  }
 ]
}