{
 "title": "Incident Priority Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory Usage Heap",
   "type": "graph",
   "description": "Heap Memory Usage as reported by JVM",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",job=\"{{ project_admin }}-incident-priority-service\"}) by (pod)",
     "legendFormat": "Used heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\",job=\"{{ project_admin }}-incident-priority-service\"}) by (pod)",
     "legendFormat": "Max heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\",job=\"{{ project_admin }}-incident-priority-service\"}) by (pod)",
     "legendFormat": "Committed heap {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage Non Heap",
   "type": "graph",
   "description": "Non Heap Memory Usage as reported by JVM",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",job=\"{{ project_admin }}-incident-priority-service\"}) by (pod)",
     "legendFormat": "Used non heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\",job=\"{{ project_admin }}-incident-priority-service\"}) by (pod)",
     "legendFormat": "Max non heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\",job=\"{{ project_admin }}-incident-priority-service\"}) by (pod)",
     "legendFormat": "Committed non heap {{pod}}"
    }
   ]
  },
  {
   "title": "Memory OpenShift",
   "type": "graph",
   "description": "Container Memory usage as reported by OpenShift",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'{{ project_admin }}-incident-priority-service-.*',namespace='{{ namespace_services }}',container='',}) BY (pod, namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage JVM",
   "type": "graph",
   "description": "CPU usage as reported by the JVM",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"{{ project_admin }}-incident-priority-service\"}",
     "legendFormat": "System {{pod}}"
    },
    {
     "expr": "process_cpu_usage{job=\"{{ project_admin }}-incident-priority-service\"}",
     "legendFormat": "Process {{pod}}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"{{ project_admin }}-incident-priority-service\"}[15m])",
     "legendFormat": "Process Avg 15m {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage OpenShift",
   "type": "graph",
   "description": "Total CPU usage as reported by OpenShift in millicore",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "millicore" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"{{ namespace_services }}\", pod=~\"{{ project_admin }}-incident-priority-service-.*\"}*1000",
     "legendFormat": "CPU total {{pod}}"
    }
   ]
  },
  {
   "title": "GC Rate per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Rate per minute" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"{{ project_admin }}-incident-priority-service\"}[1m])*60",
     "legendFormat": "GC Rate {{action}} {{cause}} {{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_pause_seconds_sum{job=\"{{ project_admin }}-incident-priority-service\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"{{ project_admin }}-incident-priority-service\"}[1m]))*1000",
     "legendFormat": "{{action}} {{cause}} {{pod}}"
    }
   ]
  },
  {
   "title": "Rules Execution Latency Priority Assignment",
   "type": "graph",
   "description": "Latency of priority assignment rules executions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg((rules:assignment:sum:rate1m/rules:assignment:count:rate1m)*1000)",
     "legendFormat": "Average"
    },
    {
     "expr": "max((rules:assignment:sum:rate1m/rules:assignment:count:rate1m)*1000)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Rules Execution Throughput Priority Assignment",
   "type": "graph",
   "description": "Average number of priority assignment rules executions per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "avg(rules:assignment:count:rate1m)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Rules Execution Latency Priority Query",
   "type": "graph",
   "description": "Latency of priority query rules executions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg((rules:query:sum:rate1m/rules:query:count:rate1m)*1000)",
     "legendFormat": "Average"
    },
    {
     "expr": "max((rules:query:sum:rate1m/rules:query:count:rate1m)*1000)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Rules Execution Throughput Priority Query",
   "type": "graph",
   "description": "Average number of priority query rules executions per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    { "expr": "avg(rules:query:count:rate1m)", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Kafka Messages Consumed ",
   "type": "graph",
   "description": "Number of Kafka messages consumed.\nCalculated as per-second average rate over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "kafka:messages_consumed:total:rate1m{job=\"{{ project_admin }}-incident-priority-service\", pod=~\"{{ project_admin }}-incident-priority-service-.*\"}",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag over Messages In/Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "lag in offsets" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"incident-priority\", topic=\"topic-incident-event\"})",
     "legendFormat": "Offset lag"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"topic-incident-event\"}[1m]))",
     "legendFormat": "Msg in"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"incident-priority\", topic=\"topic-incident-event\"}[1m])/60)",
     "legendFormat": "Msg consumed"
    }
   ]
  },
  {
   "title": "HTTP Requests Latency",
   "type": "graph",
   "description": "HTTP request latency for the '/priority/:incident' path measured over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(vertx:http_responsetime:sum:rate1m/vertx:http_responsetime:count:rate1m{job=\"{{ project_admin }}-incident-priority-service\", path=\"/priority/:incidentId\"})*1000",
     "legendFormat": "code {{code}} - {{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request Throughput",
   "type": "graph",
   "description": "HTTP request throughput for the '/priority/:incident' path measured over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "vertx:http_responsetime:count:rate1m{job=\"{{ project_admin }}-incident-priority-service\", path=\"/priority/:incidentId\"}",
     "legendFormat": "code {{code}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Incidents in KIE Session",
   "type": "graph",
   "description": "Number of Incidents in KIE Session.\nCalculated as the average and the maximum over the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kiesession_incidents[1m])/count_over_time(kiesession_incidents[1m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "max_over_time(kiesession_incidents[1m])",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Vertx EventBus Throughput",
   "type": "graph",
   "description": "Throughput of messages through the Vertx Event Bus",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "rate(vertx_eventbus_delivered_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}