{
 "title": "Incident Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory Usage Heap",
   "type": "graph",
   "description": "Heap Memory Usage as reported by JVM",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",job=\"{{ project_admin }}-incident-service\"}) by (pod)",
     "legendFormat": "Used heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\",job=\"{{ project_admin }}-incident-service\"}) by (pod)",
     "legendFormat": "Max heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\",job=\"{{ project_admin }}-incident-service\"}) by (pod)",
     "legendFormat": "Committed heap {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage Non Heap",
   "type": "graph",
   "description": "Non Heap Memory Usage as reported by JVM",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",job=\"{{ project_admin }}-incident-service\"}) by (pod)",
     "legendFormat": "Used non heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\",job=\"{{ project_admin }}-incident-service\"}) by (pod)",
     "legendFormat": "Max non heap {{pod}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\",job=\"{{ project_admin }}-incident-service\"}) by (pod)",
     "legendFormat": "Committed non heap {{pod}}"
    }
   ]
  },
  {
   "title": "Memory OpenShift",
   "type": "graph",
   "description": "Container Memory usage as reported by OpenShift",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~'{{ project_admin }}-incident-service-.*',namespace='{{ project_admin }}-er-demo',container='',}) BY (pod, namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage JVM",
   "type": "graph",
   "description": "CPU usage as reported by the JVM",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"{{ project_admin }}-incident-service\"}",
     "legendFormat": "System {{pod}}"
    },
    {
     "expr": "process_cpu_usage{job=\"{{ project_admin }}-incident-service\"}",
     "legendFormat": "Process {{pod}}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"{{ project_admin }}-incident-service\"}[15m])",
     "legendFormat": "Process Avg 15m {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage OpenShift",
   "type": "graph",
   "description": "Total CPU usage as reported by OpenShift in millicore",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "millicore" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"{{ project_admin }}-er-demo\", pod=~\"{{ project_admin }}-incident-service-.*\"}*1000",
     "legendFormat": "CPU total {{pod}}"
    }
   ]
  },
  {
   "title": "GC Rate per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Rate per minute" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"{{ project_admin }}-incident-service\"}[1m])*60",
     "legendFormat": "GC Rate {{action}} {{cause}} {{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_pause_seconds_sum{job=\"{{ project_admin }}-incident-service\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"{{ project_admin }}-incident-service\"}[1m]))*1000",
     "legendFormat": "{{action}} {{cause}} {{pod}}"
    }
   ]
  },
  {
   "title": "Incidents Created Latency",
   "type": "graph",
   "description": "Latency of incidents created",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(incident_service:http:server:sum:rate1m{uri=\"/incidents\", method=\"POST\"}/incident_service:http:server:count:rate1m{uri=\"/incidents\", method=\"POST\"})*1000",
     "legendFormat": "Latency {{pod}}"
    },
    {
     "expr": "avg((rules:query:sum:rate1m/rules:query:count:rate1m)*1000)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Incidents Created Throughput",
   "type": "graph",
   "description": "Number of incidents created per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "incident_service:http:server:count:rate1m{uri=\"/incidents\", method=\"POST\"}",
     "legendFormat": "Throughput {{pod}}"
    }
   ]
  },
  {
   "title": "JDBC Connection Pool",
   "type": "graph",
   "description": "Max connections, average active connections over the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "number" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(jdbc_connections_active{job=\"{{ project_admin }}-incident-service\"}[1m])",
     "legendFormat": "Avg Active {{pod}}"
    },
    {
     "expr": "jdbc_connections_max{job=\"{{ project_admin }}-incident-service\"}",
     "legendFormat": "Max {{pod}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag over Messages In/Consumed topic-incident-command",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "lag in offsets" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"incident-service\", topic=\"topic-incident-command\"})",
     "legendFormat": "Offset lag"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"topic-incident-command\"}[1m]))",
     "legendFormat": "Msg in"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=\"incident-service\", topic=\"topic-incident-command\"}[1m])/60)",
     "legendFormat": "Msg consumed"
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Rate and Latency",
   "type": "graph",
   "description": "Left: average and maximum time taken for a fetch request, measured in milliseconds.\nRight: number of fetch requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_latency_avg_seconds{job=\"{{ project_admin }}-incident-service\"} * 1000) by(pod)",
     "legendFormat": "Avg Fetch {{pod}}"
    },
    {
     "expr": "avg(kafka_consumer_fetch_latency_max_seconds{job=\"{{ project_admin }}-incident-service\"} * 1000) by(pod)",
     "legendFormat": "Max Fetch {{pod}}"
    },
    {
     "expr": "sum(rate(kafka_consumer_fetch_total_requests_total{job=\"{{ project_admin }}-incident-service\"}[1m])) by(pod)",
     "legendFormat": "Fetch Rate {{pod}}"
    }
   ]
  },
  {
   "title": "Kafka Records Consumed",
   "type": "graph",
   "description": "Right: rate of records consumed per second \nLeft: average number of record per request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "records per second" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_records_per_request_avg_records{job=\"{{ project_admin }}-incident-service\"}) by (pod, topic)",
     "legendFormat": "Records/request {{pod}}"
    },
    {
     "expr": "sum(rate(kafka_consumer_records_consumed_total_records_total{job=\"{{ project_admin }}-incident-service\"}[1m])) by(pod, topic)",
     "legendFormat": "Records consumed {{pod}}"
    }
   ]
  },
  {
   "title": "Partitions topic-incident-command",
   "type": "graph",
   "description": "Number of partitions for the topic-incident-command topic per pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "partitions" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_assigned_partitions{job=\"{{ project_admin }}-incident-service\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}