{
 "title": "Mission Commander KPIs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 },
   "content": "\n# Mission Commander KPIs\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "select sum(numberrescued) from missionreport"
    }
   ]
  },
  {
   "title": "Total Rescued ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select now() as time, sum(numberrescued) from missionreport"
    }
   ]
  },
  {
   "title": "Top Responders",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "select now() as time, sum(numberrescued), responderfullname from missionreport group by responderfullname order by sum desc limit 5\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 17, "x": 0, "y": 10 },
   "content": "\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "select (responderdistancetotal / responsetimesecondstotal * 3.6) as response_velocity_km_hr, responderfullname, incidentId, processinstanceid from MissionReport order by response_velocity_km_hr desc limit 10;"
    }
   ]
  },
  {
   "title": "Fastest Travel Velocities",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select (responderdistancetotal / responsetimesecondstotal * 3.6) as response_velocity_km_hr, responderfullname, incidentId, processinstanceid from MissionReport order by response_velocity_km_hr desc limit 10;"
    }
   ]
  }
 ]
}