---

- name: "create operatorgroup in {{ namespace }}"
  import_role:
    name: operatorgroup
  vars:
    operatorgroup_name: "{{ namespace }}"
    operatorgroup_namespace: "{{ namespace }}"
    operatorgroup_target_namespace: "{{ namespace }}"

- name: "deploy apicurio registry operator in {{ namespace }}"
  import_role:
    name: operator_olm
  vars:
    operator_name: apicurio-registry
    packagemanifest: "{{ apicurio_registry_operator_packagemanifest }}"
    subscription_channel: ""
    subscription_namespace: "{{ namespace }}"
    subscription_name: "{{ apicurio_registry_operator_subscription_name }}"
    automatic_installplan_approval: "{{ apicurio_registry_operator_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ apicurio_registry_operator_subscription_starting_csv }}"
    csv_prefix: "{{ apicurio_registry_operator_csv_prefix }}"

- name: "wait until apicurio registry operator is active"
  oc_obj:
    state: list
    oc_binary: "{{ openshift_cli }}"
    kind: Deployment
    name: "{{ apicurio_registry_operator_deployment_name }}"
    namespace: "{{ namespace }}"
  register: r_apicurio_registry_operator_deployment
  retries: 30
  delay: 10
  changed_when: false
  until:
    - r_apicurio_registry_operator_deployment.ansible_module_results.results[0].status.readyReplicas is defined
    - r_apicurio_registry_operator_deployment.ansible_module_results.results[0].status.replicas is defined
    - >-
      r_apicurio_registry_operator_deployment.ansible_module_results.results[0].status.readyReplicas ==
      r_apicurio_registry_operator_deployment.ansible_module_results.results[0].status.replicas

- name: copy apicurio kafka topic templates
  template:
    src: "{{ resources_dir }}/{{ apicurio_registry_kafka_topic_template }}"
    dest: "{{ work_dir }}/{{ item }}.yml"
  vars:
    kafka_topic_name: "{{ item }}"
    kafka_topic_kafka_cluster: "{{ apicurio_registry_kafka_cluster }}"
    kafka_topic_partitions: "{{ apicurio_registry_kafka_topic_partitions }}"
    kafka_topic_replicas: "{{ apicurio_registry_kafka_topic_replicas }}"
    kafka_topic_config: "{{ apicurio_registry_kafka_topic_config }}"
  loop:
    - "{{ apicurio_registry_kafka_topic_name_globalid }}"
    - "{{ apicurio_registry_kafka_topic_name_storage }}"

- name: create kafka topics for apicurio registry
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: kafkatopic
    namespace: "{{ namespace_kafka_cluster }}"
    name: "{{ item }}"
    files:
      - "{{ work_dir }}/{{ item }}.yml"
  loop:
    - "{{ apicurio_registry_kafka_topic_name_globalid }}"
    - "{{ apicurio_registry_kafka_topic_name_storage }}"

- name: copy apicurio cr template
  template:
    src: "{{ resources_dir }}/{{ apicurio_registry_cr_template }}"
    dest: "{{ work_dir }}/{{ apicurio_registry_cr_template }}"

- name: deploy apicurio registry cr
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: ApicurioRegistry
    namespace: "{{ namespace }}"
    name: "{{ apicurio_registry_cr }}"
    files: 
      - "{{ work_dir }}/{{ apicurio_registry_cr_template }}"
