---
- name: copy apicurio kafka topic templates
  template:
    src: "{{ resources_dir }}/{{ apicurio_registry_kafka_topic_template }}"
    dest: "{{ work_dir }}/{{ item }}.yml"
  vars:
    kafka_topic_name: "{{ item }}"
    kafka_topic_kafka_cluster: "{{ apicurio_registry_kafka_cluster }}"
    kafka_topic_partitions: "{{ apicurio_registry_kafka_topic_partitions }}"
    kafka_topic_replicas: "{{ apicurio_registry_kafka_topic_replicas }}"
    kafka_topic_config: "{{ apicurio_registry_kafka_topic_config }}"
  loop:
    - "{{ apicurio_registry_kafka_topic_name_globalid }}"
    - "{{ apicurio_registry_kafka_topic_name_storage }}"

- name: create kafka topics for apicurio registry
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: kafkatopic
    namespace: "{{ namespace_kafka_cluster }}"
    name: "{{ item }}"
    files:
      - "{{ work_dir }}/{{ item }}.yml"
  loop:
    - "{{ apicurio_registry_kafka_topic_name_globalid }}"
    - "{{ apicurio_registry_kafka_topic_name_storage }}"

- name: copy apicurio cr template
  template:
    src: "{{ resources_dir }}/{{ apicurio_registry_cr_template }}"
    dest: "{{ work_dir }}/{{ apicurio_registry_cr_template }}"

- name: deploy apicurio registry cr
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: ApicurioRegistry
    namespace: "{{ namespace }}"
    name: "{{ apicurio_registry_cr }}"
    files: 
      - "{{ work_dir }}/{{ apicurio_registry_cr_template }}"
