---

- name: deploy apicurio registry cr
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: ApicurioRegistry
    namespace: "{{ namespace }}"
    name: "{{ apicurio_registry_cr }}"

- name: remove kafka topics for apicurio registry
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: kafkatopic
    namespace: "{{ namespace_kafka_cluster }}"
    name: "{{ item }}"
  loop:
    - "{{ apicurio_registry_kafka_topic_name_globalid }}"
    - "{{ apicurio_registry_kafka_topic_name_storage }}"
  
- name: remove apicurio operator deployment
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: deployment
    name: "{{ apicurio_registry_operator_deployment }}"
    namespace: "{{ namespace }}"    

- name: remove rolebinding for apicurio registry operator
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: rolebinding
    namespace: "{{ namespace }}"
    name: apicurio-registry-operator

- name: remove role for apicurio registry operator
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: role
    name: apicurio-registry-operator
    namespace: "{{ namespace }}"

- name: "remove {{ service_account }} service account"
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"
