---

- name: remove apicurio registry cr
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: ApicurioRegistry
    namespace: "{{ namespace }}"
    name: "{{ apicurio_registry_cr }}"

- name: remove kafka topics for apicurio registry
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: kafkatopic
    namespace: "{{ namespace_kafka_cluster }}"
    name: "{{ item }}"
  loop:
    - "{{ apicurio_registry_kafka_topic_name_globalid }}"
    - "{{ apicurio_registry_kafka_topic_name_storage }}"

- name: "delete apicurio registry operator in {{ namespace }}"
  import_role:
    name: operator_olm
    tasks_from: uninstall
  vars:
    operator_name: apicurio-registry
    subscription_namespace: "{{ namespace }}"
    subscription_name: "{{ apicurio_registry_operator_subscription_name }}"
    csv_prefix: "{{ apicurio_registry_operator_csv_prefix }}"
