---

- name: Deploy AMQ Streams Operator
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/kafka_cluster.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_amq_streams_operator }}"
        resources_dir: "{{ resources_base_dir }}/amq-streams"
        work_dir_name: amq-streams-operator
    - include_role:
        name: amq_streams_operator
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: amq_streams_operator
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"