---

- name: Deploy the Apicurio registry
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_tools }}"
        resources_dir: "{{ resources_base_dir }}/apicurio-registry"
        work_dir_name: apicurio-registry
    - include_role:
        name: ../roles/apicurio_registry
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/apicurio_registry
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"