---

- name: Deploy Emergency Console App
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/sso.yml
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml
    - group_vars/sso_realm.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_services }}"
        resources_dir: "{{ resources_base_dir }}/emergency-console"
        work_dir_name: emergency-console
    - include_role:
        name: ../roles/openshift_emergency_console
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_emergency_console
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"