---

- name: Deploy Incident Finder Service
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_services }}"
        resources_dir: "{{ resources_base_dir }}/incident-finder-service"
        work_dir_name: incident-finder-service
    - include_role:
        name: ../roles/incident_finder_service
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/incident_finder_service
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"