---

- name: Deploy Emergency Response Demo application
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/kafka_cluster.yml
    - group_vars/tools.yml
    - group_vars/datagrid.yml
    - group_vars/postgresql.yml
    - group_vars/sso.yml
    - group_vars/monitoring.yml
    - group_vars/3scale.yml

  tasks:
    - include_role:
        name: ../roles/openshift_install
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/openshift_install
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
    - include_role:
        name: ../roles/openshift_install
        tasks_from: reset
      when: >
        ACTION is defined and
        ACTION|trim() == "reset"
