---

# https://github.com/obsidiandynamics/kafdrop

- name: Deploy kafdrop
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/kafka_cluster.yml
    - group_vars/services.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_kafka_cluster }}"
        resources_dir: "{{ resources_base_dir }}/kafdrop"
        work_dir_name: kafdrop
    - include_role:
        name: ../roles/openshift_kafdrop
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "create"
    - include_role:
        name: ../roles/openshift_kafdrop
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
