---

- name: Deploy Kafka Connect
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/kafka_cluster.yml
    - group_vars/postgresql.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_kafka_cluster }}"
        resources_dir: "{{ resources_base_dir }}/kafka-connect"
        work_dir_name: kafka-connect
    - include_role:
        name: ../roles/openshift_kafka_connect
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "create"
    - include_role:
        name: ../roles/openshift_kafka_connect
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"