---

- name: Deploy Knative Resources
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - set_fact:
        namespace: "{{ namespace_knativeserving }}"
        work_dir_name: knative
        resources_dir: "{{ resources_base_dir }}/knative"
    - include_role:
        name: knative
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "create"
    - include_role:
        name: knative
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
