---

- name: Deploy Responder Simulator Service
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/services.yml
    - group_vars/kafka_cluster.yml
    - group_vars/datagrid.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_services }}"
        resources_dir: "{{ resources_base_dir }}/responder-simulator-quarkus"
        work_dir_name: responder-simulator-quarkus
    - include_role:
        name: ../roles/responder_simulator_quarkus
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/responder_simulator_quarkus
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"