---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ image_imagestream_name }}
  labels:
    app: {{ application_name }}
spec:
  dockerImageRepository: {{ disaster_simulator_service_image }}