---

- name: "delete Kafka servicemonitor resource"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: emergency-response-kafka
    namespace: "{{ namespace }}"
    kind: ServiceMonitor

- name: "delete application servicemonitor resource"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: emergency-response-services
    namespace: "{{ namespace }}"
    kind: ServiceMonitor

- name: "delete actuator servicemonitor resource"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: emergency-response-services-actuator
    namespace: "{{ namespace }}"
    kind: ServiceMonitor

- name: "delete GrafanaDashboard emergency-response-dashboard"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: emergency-response-dashboard
    namespace: "{{ namespace_monitoring }}"
    kind: GrafanaDashboard

- name: "delete grafana dashboard mission-commander-kpis"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: mission-commander-kpis
    namespace: "{{ namespace_monitoring }}"
    kind: GrafanaDashboard

- name: "delete grafana datasource ds-dw-postgresql"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: ds-dw-postgresql
    namespace: "{{ namespace_monitoring }}"
    kind: GrafanaDataSource

- name: "delete clusterrole get-namespaces clusterrolebinding for user {{ project_admin}} "
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ project_admin }}-get-namespaces"
    kind: clusterrolebinding

- name: "delete openshift monitoring grafana datasource"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: prometheus-openshift-monitoring
    namespace: "{{ namespace_monitoring }}"
    kind: GrafanaDataSource

- name: "delete incident priority service grafana dashboard"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: incident-priority-service-dashboard
    namespace: "{{ namespace_monitoring }}"
    kind: GrafanaDashboard

- name: "delete incident priority service prometheus rules"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: incident-priority-service-prometheus-rules
    namespace: "{{ namespace_monitoring }}"
    kind: PrometheusRule

- name: "delete incident service prometheus rules"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: incident-service-prometheus-rules
    namespace: "{{ namespace_monitoring }}"
    kind: PrometheusRule
