apiVersion: v1
kind: Secret
metadata:
  name: dg-connect-secret
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
    - username: {{ datagrid_application_user }}
      password: {{ datagrid_application_password }}
    - username: {{ datagrid_operator_user }}
      password: {{ datagrid_operator_password }}
