apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ service_account_role_name }}
  labels:
    app: {{ application_name }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch