---

- name: delete postgresql dc
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ dw_postgresql_application_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: delete postgresql service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ dw_postgresql_application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete postgresql pvc
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ dw_postgresql_application_name}}"
    namespace: "{{ namespace }}"
    kind: pvc

- name: delete postgresql secret
  oc_secret:
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace }}"
    name: "{{ dw_postgresql_application_name }}"
    state: absent

- name: delete postgresql init configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ postgresql_init_configmap }}"
    namespace: "{{ namespace }}"

- name: delete {{ postgresql_service_account }} service account
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ postgresql_service_account }}"
    namespace: "{{ namespace }}"

- name: "delete {{ cm_name }} configmap"
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ cm_name }}"
    namespace: "{{ namespace }}"

- name: "delete imagestream {{ dw_application_name }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ dw_application_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream

- name: "delete dc {{ dw_application_name }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ dw_application_name }}"
    namespace: "{{ namespace }}"
    kind: deploymentconfig

- name: "delete service {{ dw_application_name }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ dw_application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: remove buildconfig
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ buildconfig_name }}"
    namespace: "{{ namespace_tools }}"
    kind: buildconfig

- name: delete the build pipeline
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ pipeline_buildconfig_name }}"
    namespace: "{{ namespace_tools }}"
    kind: bc

- name: delete imagestream from the {{ namespace_tools }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}" 
    state: absent
    name: "{{ application_name }}" 
    namespace: "{{ namespace_tools }}" 
    kind: imagestream
