apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: {{ kafka_connector_name }}
  labels:
    strimzi.io/cluster: {{ kafka_connect }}
spec:
  class: 'io.debezium.connector.postgresql.PostgresConnector'
  tasksMax: {{ kafka_connector_tasks_max }}
  config:
    database.hostname: {{ kafka_connector_db_host }}
    database.port: '{{ kafka_connector_db_port }}'
    database.user: {{ kafka_connector_db_user }}
    database.password: '{{ kafka_connector_db_password }}'
    database.dbname: {{ kafka_connector_db_name }}
    database.server.name: {{ kafka_connector_db_server_name }}
    schema.whitelist: {{ kafka_connector_schema_whitelist }}
    table.whitelist: {{ kafka_connector_table_whitelist }}
    tombstones.on.delete : 'false'
    transforms: router
    transforms.router.type: io.debezium.transforms.outbox.EventRouter
    transforms.router.table.fields.additional.placement: 'type:header:ce_type,ce_specversion:header:ce_specversion,ce_source:header:ce_source,ce_time:header:ce_time,ce_datacontenttype:header:ce_contenttype,ce_datacontenttype:header:content-type,id:header:ce_id,ce_incidentid:header:ce_incidentid'
    transforms.router.route.topic.replacement: '${routedByValue}'
