apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ name }}
spec:
  port:
    targetPort: gateway
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ apicast_service }}
    weight: 100
  wildcardPolicy: None
