---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: apicurio-registry-operator
rules:
  - apiGroups:
      - route.openshift.io
      - apps.openshift.io
    resources:
      - routes
      - routes/custom-host
      - deploymentconfigs
    verbs:
      - '*'
  - apiGroups:
      - ""
      - "extensions"
      - route.openshift.io
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - ingresses
      - routes/custom-host
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - verbs:
      - get
      - list
      - create
      - update
      - watch
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - apicurio-registry-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - apicur.io
    resources:
      - '*'
    verbs:
      - '*'
