---

- name: "create operatorgroup in {{ namespace }}"
  import_role:
    name: operatorgroup
  vars:
    operatorgroup_namespace: "{{ namespace }}"
    operatorgroup_target_namespace: "{{ namespace }}"

- name: "deploy apicurito operator in {{ namespace }}"
  import_role:
    name: operator_olm
  vars:
    operator_name: apicurito
    packagemanifest: "{{ apicurito_operator_packagemanifest }}"
    subscription_channel: ""
    subscription_namespace: "{{ namespace }}"
    subscription_name: "{{ apicurito_subscription_name }}"
    automatic_installplan_approval: "{{ apicurito_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ apicurito_subscription_starting_csv }}"
    csv_prefix: "{{ apicurito_csv_prefix }}"

- name: "wait until apicurito operator is active"
  oc_obj:
    state: list
    oc_binary: "{{ openshift_cli }}"
    kind: Deployment
    name: "{{ apicurito_operator_deployment_name }}"
    namespace: "{{ namespace }}"
  register: r_apicurito_operator_deployment
  retries: 30
  delay: 10
  changed_when: false
  until:
    - r_apicurito_operator_deployment.ansible_module_results.results[0].status.readyReplicas is defined
    - r_apicurito_operator_deployment.ansible_module_results.results[0].status.replicas is defined
    - >-
      r_apicurito_operator_deployment.ansible_module_results.results[0].status.readyReplicas ==
      r_apicurito_operator_deployment.ansible_module_results.results[0].status.replicas

- name: copy apicurito template
  template:
    src: "{{ resources_dir }}/{{ apicurito_template }}"
    dest: "{{ work_dir }}/{{ apicurito_template }}"

- name: deploy apicurito cr
  oc_obj:
    state: present
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace }}"
    name: "{{ apicurito_name }}"
    kind: apicurito
    files:
      - "{{ work_dir }}/{{ apicurito_template }}"
