---

- name: delete apicurito cr
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    namespace: "{{ namespace }}"
    name: "{{ apicurito_name }}"
    kind: apicurito

- name: "delete apicurito operator in {{ namespace }} namespace"
  import_role:
    name: operator_olm
    tasks_from: uninstall
  vars:
    operator_name: apicurito
    subscription_namespace: "{{ namespace }}"
    subscription_name: "{{ apicurito_subscription_name }}"
    csv_prefix: "{{ apicurito_csv_prefix }}"
