---

- name: "deploy jaeger operator in {{ jaeger_operator_subscription_namespace }}"
  import_role:
    name: operator_olm
  vars:
    operator_name: jaeger-product
    packagemanifest: "{{ jaeger_operator_packagemanifest }}"
    subscription_channel: "{{ jaeger_operator_subscription_channel }}"
    subscription_namespace: "{{ jaeger_operator_subscription_namespace }}"
    subscription_name: "{{ jaeger_operator_subscription_name }}"
    automatic_installplan_approval: "{{ jaeger_operator_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ jaeger_operator_subscription_starting_csv }}"
    csv_prefix: "{{ jaeger_operator_csv_prefix }}"

- name: "wait until jaeger operator is active"
  oc_obj:
    state: list
    oc_binary: "{{ openshift_cli }}"
    kind: Deployment
    name: "{{ jaeger_operator_deployment_name }}"
    namespace: "{{ jaeger_operator_subscription_namespace }}"
  register: r_jaeger_operator_deployment
  retries: 30
  delay: 10
  changed_when: false
  until:
    - r_jaeger_operator_deployment.ansible_module_results.results[0].status.readyReplicas is defined
    - r_jaeger_operator_deployment.ansible_module_results.results[0].status.replicas is defined
    - >-
      r_jaeger_operator_deployment.ansible_module_results.results[0].status.readyReplicas ==
      r_jaeger_operator_deployment.ansible_module_results.results[0].status.replicas

- name: "copy jaeger custom resource template"
  template:
    src: "{{ resources_dir }}/{{ jaeger_cr_template }}"
    dest: "{{ work_dir }}/{{ jaeger_cr_template }}"

- name: "create jaeger custom resource"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    kind: Jaeger
    name: jaeger
    namespace: "{{ namespace }}"
    files:
      - "{{ work_dir }}/{{ jaeger_cr_template }}"