---

- name: "remove jaeger custom resource"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    kind: Jaeger
    name: jaeger
    namespace: "{{ namespace }}"

- name: "remove jaeger operator in {{ jaeger_operator_subscription_namespace }}"
  import_role:
    name: operator_olm
    tasks_from: uninstall
  vars:
    operator_name: jaeger-product
    subscription_namespace: "{{ jaeger_operator_subscription_namespace }}"
    subscription_name: "{{ jaeger_operator_subscription_name }}"
    csv_prefix: "{{ jaeger_operator_csv_prefix }}"
  when: uninstall_cluster_resources|bool == true  
    