---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator
subjects:
  - kind: ServiceAccount
    name: jaeger-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jaeger-operator