---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jaeger-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: jaeger-operator
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: jaeger-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: jaeger-operator
          ports:
            - name: metrics
              containerPort: 8383
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: {{ jaeger_operator_image }}
          args:
            - start
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: jaeger-operator
      serviceAccount: jaeger-operator
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
