---

# rhsso operator
sso_operator_subscription_template: subscription.yml
sso_operator_packagemanifest: keycloak-operator
sso_operator_deployment_name: keycloak-operator
sso_operator_subscription_name: keycloak-operator
sso_operator_subscription_channel: alpha
sso_operator_subscription_automatic_installplan_approval: false
sso_operator_subscription_starting_csv: ""
sso_operator_csv_prefix: keycloak-operator

keycloak_cr_template: keycloak-cr.yml
keycloak_route_template: keycloak-route.yml