---

- name: "deploy serverless operator in {{ namespace_serverless_operator }} namespace"
  import_role:
    name: operator_olm
  vars:
    operator_name: serverless-operator
    packagemanifest: "{{ serverless_operator_packagemanifest }}"
    subscription_channel: "{{ serverless_operator_subscription_channel }}"
    subscription_namespace: "{{ namespace_serverless_operator }}"
    subscription_name: "{{ serverless_operator_subscription_name }}"
    automatic_installplan_approval: "{{ serverless_operator_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ serverless_operator_subscription_starting_csv }}"
    csv_prefix: "{{ serverless_operator_csv_prefix }}"

- name: "wait until serverless operator is active"
  oc_obj:
    state: list
    oc_binary: "{{ openshift_cli }}"
    kind: Deployment
    name: "{{ serverless_operator_deployment_name }}"
    namespace: "{{ namespace_serverless_operator }}"
  register: r_serverless_operator_deployment
  retries: 30
  delay: 10
  changed_when: false
  until:
    - r_serverless_operator_deployment.ansible_module_results.results[0].status.readyReplicas is defined
    - r_serverless_operator_deployment.ansible_module_results.results[0].status.replicas is defined
    - >-
      r_serverless_operator_deployment.ansible_module_results.results[0].status.readyReplicas ==
      r_serverless_operator_deployment.ansible_module_results.results[0].status.replicas
