---

- name: "remove knativekafka"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    kind: KnativeKafka
    namespace: "{{ namespace_knativeeventing }}"
    name: knative-kafka

- name: "remove knativeeventing"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    kind: KnativeEventing
    namespace: "{{ namespace_knativeeventing }}"
    name: knative-eventing

- name: "Delete {{ namespace_knativeeventing }} project"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    kind: Project
    name: "{{ namespace_knativeeventing }}"

- name: "remove knativeserving"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    kind: KnativeServing
    namespace: "{{ namespace_knativeserving }}"
    name: knative-serving

- name: "Delete {{ namespace_knativeserving }} project"
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    kind: Project
    name: "{{ namespace_knativeserving }}"

- name: "delete serverless operator in {{ namespace_serverless_operator }} namespace"
  import_role:
    name: operator_olm
    tasks_from: uninstall
  vars:
    operator_name: serverless-operator
    subscription_namespace: "{{ namespace_serverless_operator }}"
    subscription_name: "{{ serverless_operator_subscription_name }}"
    csv_prefix: "{{ serverless_operator_csv_prefix }}"
